/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/features/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        base: "var(--token-color-base)",
        primary: "var(--token-color-primary)",
        accent: "var(--token-color-accent)",
      },
      fontFamily: {
        base: ["var(--token-font-family-base)", "system-ui", "sans-serif"],
        manrope: ["var(--font-manrope)", "'Manrope'", "system-ui", "-apple-system", "'Segoe UI'", "Roboto", "'Helvetica Neue'", "Arial", "sans-serif"],
      },
      fontSize: {
        "display-1": "var(--token-size-display-1)",
        "display-2": "var(--token-size-display-2)",
        h1: "var(--token-size-h1)",
        h2: "var(--token-size-h2)",
        h3: "var(--token-size-h3)",
        h4: "var(--token-size-h4)",
        h5: "var(--token-size-h5)",
        h6: "var(--token-size-h6)",
        "body-lg": "var(--token-size-body-lg)",
        "body-md": "var(--token-size-body-md)",
        "body-sm": "var(--token-size-body-sm)",
        "body-xs": "var(--token-size-body-xs)",
        overline: "var(--token-size-overline)",
        "label-lg": "var(--token-size-label-lg)",
        "label-md": "var(--token-size-label-md)",
        "label-sm": "var(--token-size-label-sm)",
      },
      lineHeight: {
        "100": "var(--token-leading-100)",
        "110": "var(--token-leading-110)",
        "115": "var(--token-leading-115)",
        "120": "var(--token-leading-120)",
        "140": "var(--token-leading-140)",
        "150": "var(--token-leading-150)",
        "160": "var(--token-leading-160)",
        "170": "var(--token-leading-170)",
      },
      fontWeight: {
        regular: "var(--token-weight-regular)",
        medium: "var(--token-weight-medium)",
        semibold: "var(--token-weight-semibold)",
        bold: "var(--token-weight-bold)",
      },
      spacing: {
        0: "var(--token-space-0)",
        4: "var(--token-space-4)",
        8: "var(--token-space-8)",
        12: "var(--token-space-12)",
        16: "var(--token-space-16)",
        24: "var(--token-space-24)",
        32: "var(--token-space-32)",
        40: "var(--token-space-40)",
        48: "var(--token-space-48)",
        64: "var(--token-space-64)",
        80: "var(--token-space-80)",
        96: "var(--token-space-96)",
        128: "var(--token-space-128)",
        160: "var(--token-space-160)",
        192: "var(--token-space-192)",
        256: "var(--token-space-256)",
      },
    },
  },
  plugins: [],
};
